from config import config, paths

import subprocess
import os
import shutil
import psutil
import math
import pathlib
import tree
import ray
import template


# multiprocessing module ray should give better performance, windows is not supported
NUM_CPUS = psutil.cpu_count(logical=False)

# preamble preloaded in preamble.fmt, saved in preamble.tex, pdf compression set to 0
CODE_DIRECTORY = pathlib.Path(__file__).resolve().parent
PREAMBLE_PATH = pathlib.PurePath(CODE_DIRECTORY, 'preamble.fmt')
PREAMBLE_PRECOMPILED = False


def precompile_preamble():
    """
    This function precompiles the preamble of the template and saves the .fmt file at the synthetic data folder.
    """

    precompile_cmd = 'pdflatex -ini -jobname="preamble" "&pdflatex preamble.tex\\dump" > ' + paths.dump
    subprocess.run(precompile_cmd, cwd=CODE_DIRECTORY, shell=True, timeout=10)


@ray.remote
def conversion(pid, offset, sequences, directory, file_count):
    """
    This function calls all functions required for the full latex to png conversion for a subset of the sequences.
    It is meant to be called for a single process. The respective subset depends on the given offset.

    :param pid: The identifier of a process i with i=0,1,2,.. .
    :param offset: The subset of indices the process will process gets computed by pid * offset - (pid+1) * offset.
    :param sequences: The list of sequences that is being processed.
    :param directory: The directory path which the png files should be written to.
    :param file_count: The amount of files already in the directory. This is required to generate file names.
    :return: The return value serves as synchronization point for ray and is of no other use.
    """

    start_index = pid * offset
    end_index = (pid + 1) * offset
    end_index = min(end_index, len(sequences))

    latex = template.get_template(sequences[start_index:end_index])
    name = str(file_count + start_index)

    file = pdflatex(latex, directory, name)
    file = pdf2png(directory, file, name)

    return True


def convert_to_png(batch, directory) -> None:
    """
    This function takes a batch of seqences or a list of batches in form of onehot encodings and converts them to
    the .png format. Lists of batches are encouraged to justify the multiprocessing overhead.

    :param sequences: An array of size (batch size, sequence length, onehot length) is expected. This function
        assumes that the given onehot encodings in the array are valid. A list of batches is also allowed.
    :param directory: The directory path where the png files will get saved. The function assumes the directory exists.
    """

    global NUM_CPUS, PREAMBLE_PATH

    if not PREAMBLE_PRECOMPILED:
        precompile_preamble()

    shutil.copyfile(PREAMBLE_PATH, directory + '/preamble.fmt')

    sequences = batch.tolist()
    trees = tree.to_trees(sequences)
    latexs = [t.latex() for t in trees]

    num_sequences = len(latexs)
    cpus_used = min(num_sequences, NUM_CPUS)
    offset = math.ceil(num_sequences / cpus_used)
    file_count = len(os.listdir(directory))

    # copy to shared memory once instead of copying to each cpu
    latexs_id = ray.put(latexs)
    offset_id = ray.put(offset)
    directory_id = ray.put(directory)
    file_count_id = ray.put(file_count)

    # no need for return value but call get for synchronisation
    ray.get([conversion.remote(pid, offset_id, latexs_id, directory_id, file_count_id) for pid in range(cpus_used)])


def clean_up(directory) -> None:
    """
    This function will delete anything but .png files in a given directory. It is usefull to remove auxiliary files
    that get generated by pdflatex.

    :param directory: The path to the directory that should be cleared.
    """

    with os.scandir(directory) as iterator:
        for entry in iterator:
            if entry.is_file() and not entry.name.endswith('.png'):
                os.remove(entry)


def pdflatex(latex, directory, name) -> str:
    """
    This function generates a .pdf file at the target location. It uses pdflatex to compile the given latex code.

    :param expr: A single latex formular string without $$ or an equation environment.
    :param directory: The directory path in which the .pdf file should be saved in.
    :param name: An unique identifier for the generated file.
    :return: Returns the full path of the generated .pdf file.
    """

    file = directory + '/' + name + '.tex'

    with open(file, 'w') as f:
        f.write(latex)

    cmd = ['pdflatex',
           '-interaction=batchmode',
           '-interaction=nonstopmode',
           file]

    subprocess.run(cmd, cwd=directory, stdout=subprocess.DEVNULL)  # errors are critical

    return file[:-3] + 'pdf'


def pdf2png(directory, file, name) -> str:
    """
    This function generates a .png file at the target location from a given .pdf file. It uses ghostscript
    internally.

    :param directory: The directory path where the target .png file is located.
    :param file: The target .pdf file which should be converted to .png format.
    :param name: The unique identifier for the generated file.
    :return: Returns the full path to the generated .png file.
    """

    cmd = ['gs',
           '-dUseCropBox',
           '-dSAFER',
           '-dBATCH',
           '-dNOPAUSE',
           '-sDEVICE=pngalpha',
           '-r90',
           '-sOutputFile=' + name + '%09d.png',
           file]

    subprocess.run(cmd, cwd=directory, stdout=subprocess.DEVNULL)  # errors are critical

    return directory + '/' + name + '.png'
